// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ai_provider_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAIProviderConfig = `-- name: GetAIProviderConfig :one
SELECT purpose, provider, base_url, model, api_key_ciphertext, timeout_ms, max_input_chars, max_context_chars, max_suggestions, enabled, updated_by, created_at, updated_at, api_protocol
FROM ai_provider_configs
WHERE purpose = $1
LIMIT 1
`

func (q *Queries) GetAIProviderConfig(ctx context.Context, purpose string) (AiProviderConfig, error) {
	row := q.db.QueryRow(ctx, getAIProviderConfig, purpose)
	var i AiProviderConfig
	err := row.Scan(
		&i.Purpose,
		&i.Provider,
		&i.BaseUrl,
		&i.Model,
		&i.ApiKeyCiphertext,
		&i.TimeoutMs,
		&i.MaxInputChars,
		&i.MaxContextChars,
		&i.MaxSuggestions,
		&i.Enabled,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiProtocol,
	)
	return i, err
}

const upsertAIProviderConfig = `-- name: UpsertAIProviderConfig :one
INSERT INTO ai_provider_configs (
    purpose,
    provider,
    api_protocol,
    base_url,
    model,
    api_key_ciphertext,
    timeout_ms,
    max_input_chars,
    max_context_chars,
    max_suggestions,
    enabled,
    updated_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
ON CONFLICT (purpose) DO UPDATE
SET provider = EXCLUDED.provider,
    api_protocol = EXCLUDED.api_protocol,
    base_url = EXCLUDED.base_url,
    model = EXCLUDED.model,
    api_key_ciphertext = EXCLUDED.api_key_ciphertext,
    timeout_ms = EXCLUDED.timeout_ms,
    max_input_chars = EXCLUDED.max_input_chars,
    max_context_chars = EXCLUDED.max_context_chars,
    max_suggestions = EXCLUDED.max_suggestions,
    enabled = EXCLUDED.enabled,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING purpose, provider, base_url, model, api_key_ciphertext, timeout_ms, max_input_chars, max_context_chars, max_suggestions, enabled, updated_by, created_at, updated_at, api_protocol
`

type UpsertAIProviderConfigParams struct {
	Purpose          string      `json:"purpose"`
	Provider         string      `json:"provider"`
	ApiProtocol      string      `json:"api_protocol"`
	BaseUrl          string      `json:"base_url"`
	Model            string      `json:"model"`
	ApiKeyCiphertext string      `json:"api_key_ciphertext"`
	TimeoutMs        int32       `json:"timeout_ms"`
	MaxInputChars    int32       `json:"max_input_chars"`
	MaxContextChars  int32       `json:"max_context_chars"`
	MaxSuggestions   int32       `json:"max_suggestions"`
	Enabled          bool        `json:"enabled"`
	UpdatedBy        pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertAIProviderConfig(ctx context.Context, arg UpsertAIProviderConfigParams) (AiProviderConfig, error) {
	row := q.db.QueryRow(ctx, upsertAIProviderConfig,
		arg.Purpose,
		arg.Provider,
		arg.ApiProtocol,
		arg.BaseUrl,
		arg.Model,
		arg.ApiKeyCiphertext,
		arg.TimeoutMs,
		arg.MaxInputChars,
		arg.MaxContextChars,
		arg.MaxSuggestions,
		arg.Enabled,
		arg.UpdatedBy,
	)
	var i AiProviderConfig
	err := row.Scan(
		&i.Purpose,
		&i.Provider,
		&i.BaseUrl,
		&i.Model,
		&i.ApiKeyCiphertext,
		&i.TimeoutMs,
		&i.MaxInputChars,
		&i.MaxContextChars,
		&i.MaxSuggestions,
		&i.Enabled,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiProtocol,
	)
	return i, err
}
