// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: automation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAutomationDraftsToday = `-- name: CountAutomationDraftsToday :one
SELECT count(*)
FROM automation_article_requests
WHERE status = 'created'
  AND created_at >= date_trunc('day', now())
`

func (q *Queries) CountAutomationDraftsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAutomationDraftsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAutomationArticleRequest = `-- name: CreateAutomationArticleRequest :one
INSERT INTO automation_article_requests (
  idempotency_key,
  request_hash,
  key_id,
  status,
  title,
  source_topic,
  source_prompt,
  generation_model,
  error_message,
  client_ip,
  user_agent
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
)
RETURNING id, idempotency_key, request_hash, key_id, status, article_id, title, source_topic, source_prompt, generation_model, error_message, client_ip, user_agent, created_at, updated_at
`

type CreateAutomationArticleRequestParams struct {
	IdempotencyKey  string `json:"idempotency_key"`
	RequestHash     string `json:"request_hash"`
	KeyID           string `json:"key_id"`
	Status          string `json:"status"`
	Title           string `json:"title"`
	SourceTopic     string `json:"source_topic"`
	SourcePrompt    string `json:"source_prompt"`
	GenerationModel string `json:"generation_model"`
	ErrorMessage    string `json:"error_message"`
	ClientIp        string `json:"client_ip"`
	UserAgent       string `json:"user_agent"`
}

func (q *Queries) CreateAutomationArticleRequest(ctx context.Context, arg CreateAutomationArticleRequestParams) (AutomationArticleRequest, error) {
	row := q.db.QueryRow(ctx, createAutomationArticleRequest,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.KeyID,
		arg.Status,
		arg.Title,
		arg.SourceTopic,
		arg.SourcePrompt,
		arg.GenerationModel,
		arg.ErrorMessage,
		arg.ClientIp,
		arg.UserAgent,
	)
	var i AutomationArticleRequest
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.KeyID,
		&i.Status,
		&i.ArticleID,
		&i.Title,
		&i.SourceTopic,
		&i.SourcePrompt,
		&i.GenerationModel,
		&i.ErrorMessage,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAutomationArticleRequestByIdempotencyKey = `-- name: GetAutomationArticleRequestByIdempotencyKey :one
SELECT id, idempotency_key, request_hash, key_id, status, article_id, title, source_topic, source_prompt, generation_model, error_message, client_ip, user_agent, created_at, updated_at
FROM automation_article_requests
WHERE idempotency_key = $1
LIMIT 1
`

func (q *Queries) GetAutomationArticleRequestByIdempotencyKey(ctx context.Context, idempotencyKey string) (AutomationArticleRequest, error) {
	row := q.db.QueryRow(ctx, getAutomationArticleRequestByIdempotencyKey, idempotencyKey)
	var i AutomationArticleRequest
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.KeyID,
		&i.Status,
		&i.ArticleID,
		&i.Title,
		&i.SourceTopic,
		&i.SourcePrompt,
		&i.GenerationModel,
		&i.ErrorMessage,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAutomationArticleRequestCreated = `-- name: MarkAutomationArticleRequestCreated :one
UPDATE automation_article_requests
SET status = 'created',
    article_id = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, idempotency_key, request_hash, key_id, status, article_id, title, source_topic, source_prompt, generation_model, error_message, client_ip, user_agent, created_at, updated_at
`

type MarkAutomationArticleRequestCreatedParams struct {
	ArticleID pgtype.UUID `json:"article_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) MarkAutomationArticleRequestCreated(ctx context.Context, arg MarkAutomationArticleRequestCreatedParams) (AutomationArticleRequest, error) {
	row := q.db.QueryRow(ctx, markAutomationArticleRequestCreated, arg.ArticleID, arg.ID)
	var i AutomationArticleRequest
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.KeyID,
		&i.Status,
		&i.ArticleID,
		&i.Title,
		&i.SourceTopic,
		&i.SourcePrompt,
		&i.GenerationModel,
		&i.ErrorMessage,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
