// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Article struct {
	ID uuid.UUID `json:"id"`
	// 标题
	Title string `json:"title"`
	// 摘要
	Summary string `json:"summary"`
	// 内容
	Content string `json:"content"`
	// 浏览量
	Views int32 `json:"views"`
	// 点赞数
	Likes int32 `json:"likes"`
	// 是否发布
	IsPublish bool `json:"is_publish"`
	// 拥有者
	Owner    uuid.UUID `json:"owner"`
	CreateAt time.Time `json:"create_at"`
	UpdateAt time.Time `json:"update_at"`
	DeleteAt time.Time `json:"delete_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreateAt     time.Time `json:"create_at"`
}

type Tag struct {
	ID int64 `json:"id"`
	// 名称
	Name string `json:"name"`
	// 文章ID
	ArticleID uuid.UUID `json:"article_id"`
	CreateAt  time.Time `json:"create_at"`
}

type User struct {
	ID              uuid.UUID `json:"id"`
	Username        string    `json:"username"`
	HashedPassword  string    `json:"hashed_password"`
	FullName        string    `json:"full_name"`
	Email           string    `json:"email"`
	IsEmailVerified bool      `json:"is_email_verified"`
	// 介绍
	About    string    `json:"about"`
	Role     string    `json:"role"`
	CreateAt time.Time `json:"create_at"`
	UpdateAt time.Time `json:"update_at"`
	DeleteAt time.Time `json:"delete_at"`
}

type VerifyEmail struct {
	ID         int64     `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreateAt   time.Time `json:"create_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}
