export const ADMIN_EDITOR_TOOLBAR_ITEMS = [
  'undo',
  'redo',
  '|',
  'heading',
  '|',
  'bold',
  'italic',
  'underline',
  'strikethrough',
  'removeFormat',
  '|',
  'bulletedList',
  'numberedList',
  'todoList',
  '|',
  'link',
  'insertImage',
  'insertTable',
  'blockQuote',
  'codeBlock',
  'horizontalLine',
  '|',
  'alignment',
] as const

export const ADMIN_EDITOR_DISALLOWED_TOOLBAR_ITEMS = [
  'fontFamily',
  'fontSize',
  'fontColor',
  'fontBackgroundColor',
  'htmlEmbed',
  'sourceEditing',
  'mediaEmbed',
  'showBlocks',
  'subscript',
  'superscript',
] as const
