import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const src = resolve(import.meta.dir, '..')

const readSource = (path: string) => readFileSync(resolve(src, path), 'utf8')

describe('admin UI polish contracts', () => {
  test('admin shell uses a collapsible flush sidebar with favicon identity and AI settings nav', () => {
    const source = readSource('views/admin/AdminLayout.vue')

    expect(source).toContain('isSidebarCollapsed')
    expect(source).toContain('isEditorRoute')
    expect(source).toContain('PanelLeftClose')
    expect(source).toContain('src="/favicon.svg"')
    expect(source).toContain('collapsed-sidebar-header')
    expect(source).not.toContain('Tags')
    expect(source).toContain("name: 'adminAiSettings'")
    expect(source).toContain('lg:grid-cols-[var(--admin-sidebar-width)_minmax(0,1fr)]')
  })

  test('admin login uses the favicon logo mark', () => {
    const source = readSource('views/admin/AdminLoginView.vue')

    expect(source).toContain('src="/favicon.svg"')
    expect(source).not.toContain("import { Tags }")
    expect(source).not.toContain('<Tags')
    expect(source).not.toContain('src="/logo.svg"')
  })

  test('article list keeps automation drafts first and renders cover thumbnails', () => {
    const source = readSource('views/admin/AdminArticleListView.vue')

    expect(source).toContain('visibleArticles')
    expect(source).toContain('sortAutomationDraftsFirst')
    expect(source).toContain('coverLabel')
    expect(source).toContain(':src="coverLabel(article)"')
    expect(source).toContain('aria-label="搜索文章"')
    expect(source).toContain('创建时间')
    expect(source).toContain('formatDate(article.created_at)')
    expect(source).toContain('date.getFullYear() <= 1')
    expect(source).not.toContain('updated_at || article.created_at')
    expect(source).not.toContain('文章编号')
    expect(source).not.toContain('<FileText')
    expect(source).not.toContain('{{ article.id }}')
    expect(source).not.toContain('快速检查文章状态、调整发布节奏')
  })

  test('article list keeps pagination and search state in the route query', () => {
    const source = readSource('views/admin/AdminArticleListView.vue')
    const editorSource = readSource('views/admin/AdminArticleEditorView.vue')
    const protoSource = readSource('../../../proto/rpc_list_articles.proto')
    const gapiSource = readSource('../../../gapi/rpc_list_articles.go')
    const sqlSource = readSource('../../../db/query/article.sql')

    expect(source).toContain('useRoute')
    expect(source).toContain('syncQueryFromRoute')
    expect(source).toContain('writeListQuery')
    expect(source).toContain("router.push({ name: 'adminArticleEdit', params: { id }, query: route.query })")
    expect(source).toContain('watch(')
    expect(source).toContain("query: { title: nextTitle || undefined, page: String(query.page) }")
    expect(editorSource).toContain('adminArticleListLocation')
    expect(editorSource).toContain("query: route.query")
    expect(protoSource).toContain('string title = 3;')
    expect(gapiSource).toContain('arg.Title = pgtype.Text')
    expect(gapiSource).toContain('CountAllArticles(ctx, arg.Title)')
    expect(sqlSource).toContain('sqlc.narg(title)')
    expect(sqlSource).toContain('CountAllArticles :one')
  })

  test('editor moves title into settings and exposes article preview modal', () => {
    const source = readSource('views/admin/AdminArticleEditorView.vue')
    const configSource = readSource('admin/editor/adminEditorConfig.ts')
    const contentCss = readSource('assets/content.css')

    expect(source).toContain('previewOpen')
    expect(source).toContain('openPreview')
    expect(source).toContain('sanitizeHtml')
    expect(source).toContain('文章预览')
    expect(source).toContain('实际阅读效果')
    expect(source).toContain('aria-label="文章标题"')
    expect(source).toContain("classList.add('admin-editor-prose', 'ck-content')")
    expect(configSource).toContain('GeneralHtmlSupport')
    expect(configSource).toContain('htmlSupport')
    expect(configSource).toContain('styles: true')
    expect(configSource).toContain('attributes: true')
    expect(configSource).toContain('classes: true')
    expect(contentCss).toContain('.admin-editor-content .ck-content h1')
    expect(contentCss).toContain('.admin-editor-content .ck-content p')
    expect(contentCss).not.toContain('margin: 2rem auto 0.85rem;')
    expect(source).not.toContain('class="h-12 rounded-archive text-base font-black sm:text-lg"')
  })

  test('admin editor prose preserves rich content styling inside the reader-width shell', () => {
    const contentCss = readSource('assets/content.css')

    expect(contentCss).toContain('.admin-editor-content .ck-content::after')
    expect(contentCss).toContain(
      '.admin-editor-content .ck.ck-editor__editable.ck-editor__editable_inline {'
    )
    expect(contentCss).toContain('overflow-wrap: break-word;')
    expect(contentCss).toContain('padding: 1.25rem 2rem 3rem;')
    expect(contentCss).not.toContain('max-width: var(--prose-measure);')
    expect(contentCss).toContain('.admin-editor-content .ck-content figure.image img')
    expect(contentCss).toContain('.admin-editor-content .ck-content figure.table')
    expect(contentCss).toContain('.admin-editor-content .ck-content th,')
    expect(contentCss).toContain('.admin-editor-content .ck-content figure.image-style-side')
    expect(contentCss).toContain('> :where(figure.table, table, pre, hr) {\n  clear: both;')
    expect(contentCss).toContain(
      '.admin-editor-frame {\n  --prose-measure: 100%;\n  display: grid;'
    )
    expect(contentCss).toContain(
      '@container (min-width: 1192px) {\n  .admin-editor-frame {\n    --prose-measure: 72ch;'
    )
    expect(contentCss).toContain(
      '.admin-editor-content .ck-content\n  > :where(h1, h2, h3, h4, h5, h6, p, ul, ol, blockquote)'
    )
  })

  test('admin editor matches reader width and fills the available workbench height', () => {
    const source = readSource('views/admin/AdminArticleEditorView.vue')
    const contentCss = readSource('assets/content.css')

    expect(source).toContain('class="admin-editor-shell"')
    expect(source).not.toContain('admin-editor-shell space-y-3')
    expect(source).toContain("class=\"admin-editor-frame")
    expect(source).toContain("class=\"admin-editor-panel")
    expect(source).toContain("class=\"admin-editor-settings")
    expect(source).toContain("class=\"sticky top-0")
    expect(source).not.toContain('2xl:grid-cols')
    expect(source).not.toContain('2xl:sticky')
    expect(contentCss).toContain('--admin-editor-header-offset')
    expect(contentCss).toContain('--admin-editor-shell-width: 820px;')
    expect(contentCss).toContain('--admin-editor-settings-width: 22rem;')
    expect(contentCss).toContain('--admin-editor-layout-gap: 1.25rem;')
    expect(contentCss).toContain('--admin-editor-page-gap: 0.75rem;')
    expect(contentCss).toContain('--admin-editor-bottom-inset: 1.25rem;')
    expect(contentCss).toContain('--admin-editor-workbench-height: calc(')
    expect(contentCss).toContain('100dvh - var(--admin-editor-header-offset)')
    expect(contentCss).toContain('- var(--admin-editor-page-gap)')
    expect(contentCss).toContain('- var(--admin-editor-bottom-inset)')
    expect(contentCss).toContain('container-type: inline-size;')
    expect(contentCss).toContain('display: flex;')
    expect(contentCss).toContain('flex-direction: column;')
    expect(contentCss).toContain('gap: var(--admin-editor-page-gap);')
    expect(contentCss).toContain('.admin-editor-frame {')
    expect(contentCss).toContain('grid-template-columns: minmax(0, 1fr);')
    expect(contentCss).toContain('.admin-editor-panel {')
    expect(contentCss).toContain('@container (min-width: 1192px) {')
    expect(contentCss).toContain(
      'grid-template-columns: minmax(0, var(--admin-editor-shell-width)) var(--admin-editor-settings-width);'
    )
    expect(contentCss).toContain('justify-content: center;')
    expect(contentCss).toContain('max-width: var(--admin-editor-shell-width);')
    expect(contentCss).toContain('max-width: var(--admin-editor-settings-width);')
    expect(source).toContain('archive-surface admin-editor-content overflow-visible')
    expect(contentCss).toContain('.admin-editor-content {')
    expect(contentCss).toContain('height: var(--admin-editor-workbench-height);')
    expect(contentCss).toContain('min-height: 32rem;')
    expect(contentCss).toContain('overflow: visible;')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-toolbar {')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-editor {')
    expect(contentCss).toContain('display: flex;')
    expect(contentCss).toContain('flex-direction: column;')
    expect(contentCss).toContain('height: 100%;')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-editor__top {')
    expect(contentCss).toContain('flex: 0 0 auto;')
    expect(contentCss).toContain('position: relative;')
    expect(contentCss).toContain('top: auto;')
    expect(contentCss).toContain('z-index: 20;')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-editor__main {')
    expect(contentCss).toContain('flex: 1 1 auto;')
    expect(contentCss).toContain('overflow-y: auto;')
    expect(contentCss).toContain('overscroll-behavior: contain;')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-sticky-panel .ck-sticky-panel__content_sticky {')
    expect(contentCss).toContain('position: static;')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-sticky-panel__placeholder {')
    expect(contentCss).toContain('display: none !important;')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-editor__editable.ck-editor__editable_inline {')
    expect(contentCss).toContain('min-height: 100%;')
    expect(contentCss).toContain('padding: 1.25rem 2rem 3rem;')
    expect(contentCss).not.toContain('padding: 1.25rem 0 3rem;')
    expect(contentCss).not.toContain('--admin-editor-workbench-height: 68dvh;')
    expect(contentCss).not.toContain('max-height: calc(100dvh - var(--admin-editor-header-offset) - 2rem);')
    expect(contentCss).not.toContain('top: var(--admin-editor-header-offset);')
    expect(contentCss).not.toContain('overflow: clip;')
  })

  test('admin editor visual details stay readable across hover, preview, and table captions', () => {
    const source = readSource('views/admin/AdminArticleEditorView.vue')
    const contentCss = readSource('assets/content.css')

    expect(contentCss).toContain('.admin-editor-content .ck.ck-button:hover:not(.ck-disabled),')
    expect(contentCss).toContain('background: rgb(var(--color-accent) / 0.12);')
    expect(contentCss).toContain('.admin-editor-content .ck-content > :first-child')
    expect(contentCss).toContain('margin-top: 0;')
    expect(contentCss).toContain('.reading-prose hr,')
    expect(contentCss).toContain('.reading-prose.ck-content.admin-preview-content hr,')
    expect(contentCss).toContain('.admin-editor-content .ck-content hr {')
    expect(contentCss).toContain('.reading-prose figure.table,')
    expect(contentCss).toContain('.admin-editor-content .ck-content figure.table {')
    expect(contentCss).toContain('overflow-x: auto;')
    expect(contentCss).toContain('overflow-y: clip;')
    expect(contentCss).toContain('.reading-prose figure.table table,')
    expect(contentCss).toContain('.admin-editor-content .ck-content figure.table table {')
    expect(contentCss).toContain('width: max-content;')
    expect(contentCss).toContain('min-width: 100%;')
    expect(contentCss).toContain('max-width: none;')
    expect(contentCss).toContain('.reading-prose figure.table > figcaption,')
    expect(contentCss).toContain('.admin-editor-content .ck-content figure.table > figcaption')
    expect(contentCss).toContain('display: block;')
    expect(contentCss).toContain('writing-mode: horizontal-tb;')
    expect(source).toContain('class="reading-prose ck-content admin-preview-content"')
  })

  test('admin routes include a dedicated AI settings page', () => {
    const routerSource = readSource('router/index.ts')
    const pageSource = readSource('views/admin/AdminAISettingsView.vue')
    const apiSource = readSource('admin/api/adminAiApi.ts')
    const typesSource = readSource('admin/types.ts')

    expect(routerSource).toContain("name: 'adminAiSettings'")
    expect(pageSource).toContain('AI 提供商')
    expect(pageSource).toContain('getAdminAIConfig')
    expect(pageSource).toContain('updateAdminAIConfig')
    expect(pageSource).toContain('listAdminAIModels')
    expect(pageSource).toContain('refreshModels')
    expect(pageSource).toContain('form.apiProtocol')
    expect(pageSource).toContain('chat/completions')
    expect(pageSource).toContain('responses')
    expect(pageSource).toContain('messages')
    expect(pageSource).toContain('提供商名称')
    expect(pageSource).toContain('刷新模型')
    expect(pageSource).toContain('@submit.prevent="saveConfig"')
    expect(pageSource).toContain('apiKeyDraft')
    expect(pageSource).toContain('clearApiKey')
    expect(apiSource).toContain('getAdminAIConfig')
    expect(apiSource).toContain('updateAdminAIConfig')
    expect(apiSource).toContain('listAdminAIModels')
    expect(typesSource).toContain('api_protocol')
    expect(typesSource).toContain('AdminAIModelsResponse')
  })
})

describe('public navigation polish contracts', () => {
  test('profile menu has outside click close and an admin backend entry', () => {
    const source = readSource('views/layout/NavBar.vue')

    expect(source).toContain('userMenuRef')
    expect(source).toContain('handleDocumentClick')
    expect(source).toContain('onBeforeUnmount')
    expect(source).toContain("userStore.userInfo?.role === 'admin'")
    expect(source).toContain("name: 'adminArticles'")
    expect(source).toContain('后台管理')
  })

  test('theme switching animates global color changes and icon controls', () => {
    const useThemeSource = readSource('composables/useTheme.ts')
    const cssSource = readSource('assets/main.css')
    const switcherSource = readSource('components/ui/ThemeSwitcher.vue')

    expect(useThemeSource).toContain('THEME_TRANSITION_CLASS')
    expect(useThemeSource).toContain('theme-transitioning')
    expect(useThemeSource).toContain('THEME_TRANSITION_MS = 320')
    expect(cssSource).toContain('html.theme-transitioning')
    expect(cssSource).toContain('320ms')
    expect(switcherSource).toContain('themeSwitcherTranslate')
    expect(switcherSource).toContain('theme-switcher-thumb')
    expect(switcherSource).not.toContain('scale-105')
  })
})
