import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const src = resolve(import.meta.dir, '..')

const readSource = (path: string) => readFileSync(resolve(src, path), 'utf8')

describe('admin UI polish contracts', () => {
  test('admin shell uses a collapsible flush sidebar with favicon identity and AI settings nav', () => {
    const source = readSource('views/admin/AdminLayout.vue')

    expect(source).toContain('isSidebarCollapsed')
    expect(source).toContain('isEditorRoute')
    expect(source).toContain('PanelLeftClose')
    expect(source).toContain('src="/favicon.svg"')
    expect(source).toContain('collapsed-sidebar-header')
    expect(source).not.toContain('Tags')
    expect(source).toContain("name: 'adminAiSettings'")
    expect(source).toContain('lg:grid-cols-[var(--admin-sidebar-width)_minmax(0,1fr)]')
  })

  test('admin login uses the favicon logo mark', () => {
    const source = readSource('views/admin/AdminLoginView.vue')

    expect(source).toContain('src="/favicon.svg"')
    expect(source).not.toContain('import { Tags }')
    expect(source).not.toContain('<Tags')
    expect(source).not.toContain('src="/logo.svg"')
  })

  test('article list keeps automation drafts first and renders shared cover thumbnails', () => {
    const source = readSource('views/admin/AdminArticleListView.vue')

    expect(source).toContain('visibleArticles')
    expect(source).toContain('sortAutomationDraftsFirst')
    expect(source).toContain('defaultArticleCoverSrc')
    expect(source).toContain('articleCoverSrc')
    expect(source).toContain('hasCustomArticleCover')
    expect(source).toContain("cover === defaultArticleCoverSrc ? '' : cover")
    expect(source).toContain('ArticleCover')
    expect(source).toContain(':src="articleCoverSrc(article)"')
    expect(source).toContain('未设置封面')
    expect(source).toContain('grid-cols-[6.5rem_minmax(0,1fr)]')
    expect(source).toContain('sm:grid-cols-[8rem_minmax(0,1fr)]')
    expect(source).toContain('lg:grid-cols-[9rem_minmax(0,1fr)]')
    expect(source).toContain('grid min-w-0 grid-cols-[6.5rem_minmax(0,1fr)] items-center')
    expect(source).toContain('@click="openArticlePreview(article)"')
    expect(source).toContain('aria-label="搜索文章"')
    expect(source).toContain('创建时间')
    expect(source).toContain('formatDate(article.created_at)')
    expect(source).toContain('date.getFullYear() <= 1')
    expect(source).not.toContain('fallback-src="/images/go.png"')
    expect(source).not.toContain('sm:w-44')
    expect(source).not.toContain('lg:w-40')
    expect(source).not.toContain('updated_at || article.created_at')
    expect(source).not.toContain('文章编号')
    expect(source).not.toContain('<FileText')
    expect(source).not.toContain('{{ article.id }}')
    expect(source).not.toContain('快速检查文章状态、调整发布节奏')
  })

  test('article list keeps pagination and search state in the route query', () => {
    const source = readSource('views/admin/AdminArticleListView.vue')
    const editorSource = readSource('views/admin/AdminArticleEditorView.vue')
    const protoSource = readSource('../../../proto/rpc_list_articles.proto')
    const gapiSource = readSource('../../../gapi/rpc_list_articles.go')
    const sqlSource = readSource('../../../db/query/article.sql')

    expect(source).toContain('useRoute')
    expect(source).toContain('syncQueryFromRoute')
    expect(source).toContain('writeListQuery')
    expect(source).toContain(
      "router.push({ name: 'adminArticleEdit', params: { id }, query: route.query })"
    )
    expect(source).toContain('watch(')
    expect(source).toContain('query: { title: nextTitle || undefined, page: String(query.page) }')
    expect(editorSource).toContain('adminArticleListLocation')
    expect(editorSource).toContain('query: route.query')
    expect(protoSource).toContain('string title = 3;')
    expect(gapiSource).toContain('arg.Title = pgtype.Text')
    expect(gapiSource).toContain('CountAllArticles(ctx, arg.Title)')
    expect(sqlSource).toContain('sqlc.narg(title)')
    expect(sqlSource).toContain('CountAllArticles :one')
  })

  test('editor moves title into settings and exposes article preview modal', () => {
    const source = readSource('views/admin/AdminArticleEditorView.vue')
    const configSource = readSource('admin/editor/adminEditorConfig.ts')
    const contentCss = readSource('assets/content.css')
    const previewDialogSource = readSource('components/article/ArticlePreviewDialog.vue')

    expect(source).toContain('previewOpen')
    expect(source).toContain('previewOverrides')
    expect(source).toContain('openPreview')
    expect(source).toContain('ArticlePreviewDialog')
    expect(previewDialogSource).toContain('文章预览')
    expect(previewDialogSource).toContain('实际阅读效果')
    expect(source).toContain('aria-label="文章标题"')
    expect(source).toContain('id="admin-article-title"')
    expect(source).toContain('id="admin-article-summary"')
    expect(source).toContain('@click.stop="requestTitleCandidates"')
    expect(source).toContain('@click.stop="requestSummaryCandidates"')
    expect(source).toContain("classList.add('admin-editor-prose', 'ck-content')")
    expect(configSource).toContain('GeneralHtmlSupport')
    expect(configSource).toContain('PasteFromMarkdownExperimental')
    expect(configSource).toContain('SourceEditing')
    expect(configSource).toContain('ShowBlocks')
    expect(configSource).not.toContain('Markdown,')
    expect(configSource).toContain('htmlSupport')
    expect(configSource).toContain('styles: true')
    expect(configSource).toContain('attributes: true')
    expect(configSource).toContain('classes: true')
    expect(contentCss).toContain('.admin-editor-content .ck-content h1')
    expect(contentCss).toContain('.admin-editor-content .ck-content p')
    expect(contentCss).not.toContain('margin: 2rem auto 0.85rem;')
    expect(source).not.toContain('class="h-12 rounded-archive text-base font-black sm:text-lg"')
  })

  test('admin editor prose preserves rich content styling inside the reader-width shell', () => {
    const contentCss = readSource('assets/content.css')

    expect(contentCss).toContain('.admin-editor-content .ck-content::after')
    expect(contentCss).toContain(
      '.admin-editor-content .ck.ck-editor__editable.ck-editor__editable_inline {'
    )
    expect(contentCss).toContain('overflow-wrap: break-word;')
    expect(contentCss).toContain('padding: 1.25rem 2rem 3rem;')
    expect(contentCss).not.toContain('max-width: var(--prose-measure);')
    expect(contentCss).toContain('.admin-editor-content .ck-content figure.image img')
    expect(contentCss).toContain('.admin-editor-content .ck-content figure.table')
    expect(contentCss).toContain('.admin-editor-content .ck-content th,')
    expect(contentCss).toContain('.admin-editor-content .ck-content figure.image-style-side')
    expect(contentCss).toContain('> :where(figure.table, table, pre, hr) {\n  clear: both;')
    expect(contentCss).toContain(
      '.admin-editor-frame {\n  --prose-measure: 100%;\n  display: grid;'
    )
    expect(contentCss).toContain(
      '@container (min-width: 1192px) {\n  .admin-editor-frame {\n    --prose-measure: 72ch;'
    )
    expect(contentCss).toContain(
      '.admin-editor-content .ck-content\n  > :where(h1, h2, h3, h4, h5, h6, p, ul, ol, blockquote)'
    )
  })

  test('admin editor matches reader width and fills the available workbench height', () => {
    const source = readSource('views/admin/AdminArticleEditorView.vue')
    const contentCss = readSource('assets/content.css')

    expect(source).toContain('class="admin-editor-shell"')
    expect(source).not.toContain('admin-editor-shell space-y-3')
    expect(source).toContain('class="admin-editor-frame')
    expect(source).toContain('class="admin-editor-panel')
    expect(source).toContain('class="admin-editor-settings')
    expect(source).toContain('class="sticky top-0')
    expect(source).not.toContain('2xl:grid-cols')
    expect(source).not.toContain('2xl:sticky')
    expect(contentCss).toContain('--admin-editor-header-offset')
    expect(contentCss).toContain('--admin-editor-shell-width: 820px;')
    expect(contentCss).toContain('--admin-editor-settings-width: 22rem;')
    expect(contentCss).toContain('--admin-editor-layout-gap: 1.25rem;')
    expect(contentCss).toContain('--admin-editor-page-gap: 0.75rem;')
    expect(contentCss).toContain('--admin-editor-bottom-inset: 1.25rem;')
    expect(contentCss).toContain('--admin-editor-workbench-height: calc(')
    expect(contentCss).toContain('100dvh - var(--admin-editor-header-offset)')
    expect(contentCss).toContain('- var(--admin-editor-page-gap)')
    expect(contentCss).toContain('- var(--admin-editor-bottom-inset)')
    expect(contentCss).toContain('container-type: inline-size;')
    expect(contentCss).toContain('display: flex;')
    expect(contentCss).toContain('flex-direction: column;')
    expect(contentCss).toContain('gap: var(--admin-editor-page-gap);')
    expect(contentCss).toContain('.admin-editor-frame {')
    expect(contentCss).toContain('grid-template-columns: minmax(0, 1fr);')
    expect(contentCss).toContain('.admin-editor-panel {')
    expect(contentCss).toContain('@container (min-width: 1192px) {')
    expect(contentCss).toContain(
      'grid-template-columns: minmax(0, var(--admin-editor-shell-width)) var(--admin-editor-settings-width);'
    )
    expect(contentCss).toContain('justify-content: center;')
    expect(contentCss).toContain('max-width: var(--admin-editor-shell-width);')
    expect(contentCss).toContain('max-width: var(--admin-editor-settings-width);')
    expect(source).toContain('archive-surface admin-editor-content overflow-visible')
    expect(contentCss).toContain('.admin-editor-content {')
    expect(contentCss).toContain('height: var(--admin-editor-workbench-height);')
    expect(contentCss).toContain('min-height: 32rem;')
    expect(contentCss).toContain('overflow: visible;')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-toolbar,')
    expect(contentCss).toContain('#comment-editor .ck.ck-toolbar {')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-editor {')
    expect(contentCss).toContain('display: flex;')
    expect(contentCss).toContain('flex-direction: column;')
    expect(contentCss).toContain('height: 100%;')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-editor__top {')
    expect(contentCss).toContain('flex: 0 0 auto;')
    expect(contentCss).toContain('position: relative;')
    expect(contentCss).toContain('top: auto;')
    expect(contentCss).toContain('z-index: 20;')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-editor__main {')
    expect(contentCss).toContain('flex: 1 1 auto;')
    expect(contentCss).toContain('overflow-y: auto;')
    expect(contentCss).toContain('overscroll-behavior: contain;')
    expect(contentCss).toContain(
      '.admin-editor-content .ck.ck-sticky-panel .ck-sticky-panel__content_sticky {'
    )
    expect(contentCss).toContain('position: static;')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-sticky-panel__placeholder {')
    expect(contentCss).toContain('display: none !important;')
    expect(contentCss).toContain(
      '.admin-editor-content .ck.ck-editor__editable.ck-editor__editable_inline {'
    )
    expect(contentCss).toContain('min-height: 100%;')
    expect(contentCss).toContain('padding: 1.25rem 2rem 3rem;')
    expect(contentCss).not.toContain('padding: 1.25rem 0 3rem;')
    expect(contentCss).not.toContain('--admin-editor-workbench-height: 68dvh;')
    expect(contentCss).not.toContain(
      'max-height: calc(100dvh - var(--admin-editor-header-offset) - 2rem);'
    )
    expect(contentCss).not.toContain('top: var(--admin-editor-header-offset);')
    expect(contentCss).not.toContain('overflow: clip;')
  })

  test('admin editor visual details stay readable across hover, preview, and table captions', () => {
    const source = readSource('views/admin/AdminArticleEditorView.vue')
    const contentCss = readSource('assets/content.css')

    expect(contentCss).toContain('.admin-editor-content .ck.ck-button:hover:not(.ck-disabled),')
    expect(contentCss).toContain('background: rgb(var(--color-accent) / 0.12);')
    expect(contentCss).toContain('.admin-editor-content .ck-content > :first-child')
    expect(contentCss).toContain('margin-top: 0;')
    expect(contentCss).toContain('.reading-prose hr,')
    expect(contentCss).toContain('.reading-prose.ck-content.admin-preview-content hr,')
    expect(contentCss).toContain('.admin-editor-content .ck-content hr {')
    expect(contentCss).toContain('.reading-prose figure.table,')
    expect(contentCss).toContain('.admin-editor-content .ck-content figure.table {')
    expect(contentCss).toContain('overflow-x: auto;')
    expect(contentCss).toContain('overflow-y: clip;')
    expect(contentCss).toContain('.reading-prose figure.table table,')
    expect(contentCss).toContain('.admin-editor-content .ck-content figure.table table {')
    expect(contentCss).toContain('width: max-content;')
    expect(contentCss).toContain('min-width: 100%;')
    expect(contentCss).toContain('max-width: none;')
    expect(contentCss).toContain('.reading-prose figure.table > figcaption,')
    expect(contentCss).toContain('.admin-editor-content .ck-content figure.table > figcaption')
    expect(contentCss).toContain('display: block;')
    expect(contentCss).toContain('writing-mode: horizontal-tb;')
    expect(source).toContain('<ArticlePreviewDialog')
    expect(source).not.toContain('class="reading-prose ck-content admin-preview-content"')
    expect(source).toContain('aiDrawerOpen')
    expect(source).toContain('aiPolishSession')
    expect(source).toContain('admin-ai-drawer')
    expect(source).toContain('replaceSelectionWithSuggestion')
    expect(source).toContain('updateAIPolishMarker')
    expect(source).toContain('rememberEditorSelection')
    expect(contentCss).toContain('.admin-ai-drawer')
  })

  test('admin AI polish interactions keep edits explicit and resilient', () => {
    const source = readSource('views/admin/AdminArticleEditorView.vue')
    const apiSource = readSource('admin/api/adminAiApi.ts')
    const contentCss = readSource('assets/content.css')

    expect(source).toContain('savedIsPublished')
    expect(source).toContain('savedPublishText')
    expect(source).toContain('coverPreviewVersion')
    expect(source).toContain('coverPreview = computed(() =>')
    expect(source).toContain('coverPreviewVersion.value ? `${cover}?t=${coverPreviewVersion.value}` : cover')
    expect(source).toContain('article.value.cover = response.data.url')
    expect(source).toContain('coverPreviewVersion.value = Date.now()')
    expect(source).not.toContain('article.value.cover = `${response.data.url}?t=${Date.now()}`')
    expect(source).toContain('aiPolishMarkerName')
    expect(source).toContain('AI_POLISH_MARKER_GROUP')
    expect(source).toContain('installAIPolishMarkerHighlight')
    expect(source).toContain('markerToHighlight')
    expect(source).toContain('model: AI_POLISH_MARKER_GROUP')
    expect(source).toContain('writer.addMarker')
    expect(source).toContain('writer.updateMarker')
    expect(source).toContain('writer.removeMarker')
    expect(source).toContain('updatePolishTargetFromSelection')
    expect(source).toContain('更新替换目标')
    expect(source).not.toContain('capturedSelectionRange')
    expect(source).not.toContain('writer.setSelection(range)')
    expect(source).toContain('lastEditorSelectionText')
    expect(source).toContain('lastEditorSelectionHtml')
    expect(source).toContain('readEditorSelectionHtml')
    expect(source).toContain('editor.model.getSelectedContent(selection)')
    expect(source).toContain('editor.data.stringify(fragment)')
    expect(source).toContain('rememberEditorSelection')
    expect(source).toContain('editor.editing.view.document.isFocused')
    expect(source).toContain('选区已失效')
    expect(source).toContain('insertSuggestionContent')
    expect(source).toContain('buildAIPolishContentPreview')
    expect(source).toContain('sourceRichText: richContext.richText')
    expect(source).toContain('sourceRichText: session?.sourceRichText')
    expect(source).toContain('replacementHtml')
    expect(source).toContain('richText: selectionSnapshot.richText')
    expect(source).toContain('inputFormat: selectionSnapshot.inputFormat')
    expect(source).toContain('plainSuggestionText')
    expect(source).toContain('openPreview({ summary: plainSuggestionText(suggestion.content) })')
    expect(source).toContain('writeRichClipboard')
    expect(source).toContain('htmlToPlainText')
    expect(source).not.toContain('const copyText')
    expect(source).not.toContain('writer.createText(suggestion.content)')
    expect(source).not.toContain('writer.setSelection(position)')
    expect(source).not.toContain('class="rounded-archive text-base font-black"')
    expect(contentCss).toContain('.admin-ai-polish-target')
    expect(apiSource).toContain('AI_POLISH_REQUEST_TIMEOUT_MS')
    expect(apiSource).toContain('timeout: AI_POLISH_REQUEST_TIMEOUT_MS')
  })

  test('article reading surfaces share the same preview and rich content contract', () => {
    const publicArticleSource = readSource('views/article/ArticleView.vue')
    const editorSource = readSource('views/admin/AdminArticleEditorView.vue')
    const listSource = readSource('views/admin/AdminArticleListView.vue')
    const readerSource = readSource('components/article/ArticleReader.vue')
    const richContentSource = readSource('components/article/ArticleRichContent.vue')
    const previewDialogSource = readSource('components/article/ArticlePreviewDialog.vue')
    const contentCss = readSource('assets/content.css')

    expect(publicArticleSource).toContain('ArticleReader')
    expect(publicArticleSource).not.toContain('sanitizedArticleContent')
    expect(editorSource).toContain('ArticlePreviewDialog')
    expect(listSource).toContain('ArticlePreviewDialog')
    expect(listSource).toContain('openArticlePreview')
    expect(listSource).toContain('previewRequestToken')
    expect(listSource).toContain('@click="openArticlePreview(article)"')
    expect(listSource).toContain('getAdminArticle(article.id, true)')
    expect(readerSource).toContain('ArticleRichContent')
    expect(readerSource).toContain('article-reader-title')
    expect(readerSource).toContain('titleClass')
    expect(readerSource).toContain("previewContent ? 'text-pretty' : 'text-balance'")
    expect(readerSource).toContain(':class="titleClass"')
    expect(readerSource).toContain('article-reader-content')
    expect(readerSource).toContain('class="article-reader-content mt-8"')
    expect(richContentSource).toContain('sanitizeHtml')
    expect(richContentSource).toContain('reading-prose')
    expect(richContentSource).toContain('ck-content')
    expect(previewDialogSource).toContain('ArticleReader')
    expect(previewDialogSource).toContain('max-w-[820px]')
    expect(contentCss).toContain('.reading-prose ul,')
    expect(contentCss).toContain('.admin-editor-content .ck-content ul {')
    expect(contentCss).toContain('list-style-type: disc;')
    expect(contentCss).toContain('list-style-type: decimal;')
    expect(contentCss).toContain('.reading-prose .todo-list,')
    expect(contentCss).toContain('.admin-editor-content .ck-content .todo-list {')
    expect(contentCss).toContain('.reading-prose .todo-list li,')
    expect(contentCss).toContain('.admin-editor-content .ck-content .todo-list li {')
    expect(contentCss).toContain('.reading-prose .todo-list .todo-list__label > input,')
    expect(contentCss).toContain(
      '.admin-editor-content .ck-content .todo-list .todo-list__label > input,'
    )
    expect(contentCss).toContain('.reading-prose .todo-list .todo-list__label > input:checked::before,')
    expect(contentCss).toContain(
      '.admin-editor-content .ck-content .todo-list .todo-list__label > input:checked::before,'
    )
    expect(contentCss).toContain(
      '.reading-prose .todo-list .todo-list__label .todo-list__label__description,'
    )
    expect(contentCss).toContain('.reading-prose .todo-list li::marker,')
    expect(contentCss).toContain('.admin-editor-content .ck-content .todo-list li::marker {')
    expect(contentCss).toContain('width: min(100%, var(--prose-measure));')
    expect(contentCss).toContain('word-break: normal;')
  })

  test('comment editor shares ck toolbar styling with the admin editor', () => {
    const commentEditorSource = readSource('components/article/CommentEditor.vue')
    const contentCss = readSource('assets/content.css')

    expect(contentCss).toContain('.admin-editor-content .ck.ck-toolbar,')
    expect(contentCss).toContain('#comment-editor .ck.ck-toolbar {')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-button:hover:not(.ck-disabled),')
    expect(contentCss).toContain('#comment-editor .ck.ck-button:hover:not(.ck-disabled),')
    expect(contentCss).toContain('background: rgb(var(--color-accent) / 0.12);')
    expect(contentCss).toContain('color: rgb(var(--color-foreground));')
    expect(contentCss).toContain('#comment-editor .ck.ck-button.ck-on,')
    expect(contentCss).toContain('color: rgb(var(--color-accent));')
    expect(contentCss).toContain('#comment-editor .ck.ck-button:hover:not(.ck-disabled) .ck-icon,')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-dropdown__panel,')
    expect(contentCss).toContain('#comment-editor .ck.ck-dropdown__panel {')
    expect(contentCss).toContain('.admin-editor-content .ck.ck-dropdown__panel .ck.ck-list,')
    expect(contentCss).toContain('#comment-editor .ck.ck-dropdown__panel .ck.ck-list {')
    expect(contentCss).toContain(
      '.admin-editor-content .ck.ck-dropdown__panel .ck.ck-list__item > .ck-button,'
    )
    expect(contentCss).toContain(
      '#comment-editor .ck.ck-dropdown__panel .ck.ck-list__item > .ck-button,'
    )
    expect(contentCss).toContain(
      '#comment-editor .ck.ck-dropdown__panel .ck.ck-list__item > .ck-button:hover:not(.ck-disabled),'
    )
    expect(contentCss).toContain(
      '#comment-editor .ck.ck-dropdown__panel .ck.ck-list__item > .ck-button.ck-on'
    )
    expect(commentEditorSource).toContain('id="comment-editor"')
    expect(commentEditorSource).not.toContain(':deep(.ck-toolbar)')
  })

  test('admin routes include a dedicated AI settings page', () => {
    const routerSource = readSource('router/index.ts')
    const pageSource = readSource('views/admin/AdminAISettingsView.vue')
    const apiSource = readSource('admin/api/adminAiApi.ts')
    const typesSource = readSource('admin/types.ts')

    expect(routerSource).toContain("name: 'adminAiSettings'")
    expect(pageSource).toContain('AI 提供商')
    expect(pageSource).toContain('getAdminAIConfig')
    expect(pageSource).toContain('updateAdminAIConfig')
    expect(pageSource).toContain('listAdminAIModels')
    expect(pageSource).toContain('refreshModels')
    expect(pageSource).toContain('form.apiProtocol')
    expect(pageSource).toContain('chat/completions')
    expect(pageSource).toContain('responses')
    expect(pageSource).toContain('messages')
    expect(pageSource).toContain('提供商名称')
    expect(pageSource).toContain('刷新模型')
    expect(pageSource).toContain('@submit.prevent="saveConfig"')
    expect(pageSource).toContain('apiKeyDraft')
    expect(pageSource).toContain('clearApiKey')
    expect(pageSource).toContain('promptTemplates')
    expect(pageSource).toContain('defaultPromptTemplates')
    expect(pageSource).toContain('高级提示词')
    expect(pageSource).toContain('resetPromptTemplate')
    expect(pageSource).toContain('resetAllPromptTemplates')
    expect(apiSource).toContain('getAdminAIConfig')
    expect(apiSource).toContain('updateAdminAIConfig')
    expect(apiSource).toContain('listAdminAIModels')
    expect(typesSource).toContain('api_protocol')
    expect(typesSource).toContain('prompt_templates')
    expect(typesSource).toContain('default_prompt_templates')
    expect(typesSource).toContain('AdminAIModelsResponse')
  })
})

describe('public navigation polish contracts', () => {
  test('profile menu has outside click close and an admin backend entry', () => {
    const source = readSource('views/layout/NavBar.vue')

    expect(source).toContain('userMenuRef')
    expect(source).toContain('handleDocumentClick')
    expect(source).toContain('onBeforeUnmount')
    expect(source).toContain("userStore.userInfo?.role === 'admin'")
    expect(source).toContain("name: 'adminArticles'")
    expect(source).toContain('后台管理')
  })

  test('theme switching animates global color changes and icon controls', () => {
    const useThemeSource = readSource('composables/useTheme.ts')
    const cssSource = readSource('assets/main.css')
    const switcherSource = readSource('components/ui/ThemeSwitcher.vue')

    expect(useThemeSource).toContain('THEME_TRANSITION_CLASS')
    expect(useThemeSource).toContain('theme-transitioning')
    expect(useThemeSource).toContain('THEME_TRANSITION_MS = 320')
    expect(cssSource).toContain('html.theme-transitioning')
    expect(cssSource).toContain('320ms')
    expect(switcherSource).toContain('themeSwitcherTranslate')
    expect(switcherSource).toContain('theme-switcher-thumb')
    expect(switcherSource).not.toContain('scale-105')
  })
})
