// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: rpc_logout_admin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogoutAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutAdminRequest) Reset() {
	*x = LogoutAdminRequest{}
	mi := &file_rpc_logout_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutAdminRequest) ProtoMessage() {}

func (x *LogoutAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_logout_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutAdminRequest.ProtoReflect.Descriptor instead.
func (*LogoutAdminRequest) Descriptor() ([]byte, []int) {
	return file_rpc_logout_admin_proto_rawDescGZIP(), []int{0}
}

type LogoutAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutAdminResponse) Reset() {
	*x = LogoutAdminResponse{}
	mi := &file_rpc_logout_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutAdminResponse) ProtoMessage() {}

func (x *LogoutAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_logout_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutAdminResponse.ProtoReflect.Descriptor instead.
func (*LogoutAdminResponse) Descriptor() ([]byte, []int) {
	return file_rpc_logout_admin_proto_rawDescGZIP(), []int{1}
}

func (x *LogoutAdminResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_logout_admin_proto protoreflect.FileDescriptor

var file_rpc_logout_admin_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x72, 0x70, 0x63, 0x5f, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x5f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x14, 0x0a, 0x12,
	0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x2f, 0x0a, 0x13, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x65, 0x6e, 0x2f, 0x6e,
	0x6f, 0x73, 0x74, 0x61, 0x6c, 0x67, 0x69, 0x61, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_rpc_logout_admin_proto_rawDescOnce sync.Once
	file_rpc_logout_admin_proto_rawDescData []byte
)

func file_rpc_logout_admin_proto_rawDescGZIP() []byte {
	file_rpc_logout_admin_proto_rawDescOnce.Do(func() {
		file_rpc_logout_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_logout_admin_proto_rawDesc), len(file_rpc_logout_admin_proto_rawDesc)))
	})
	return file_rpc_logout_admin_proto_rawDescData
}

var file_rpc_logout_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_logout_admin_proto_goTypes = []any{
	(*LogoutAdminRequest)(nil),  // 0: pb.LogoutAdminRequest
	(*LogoutAdminResponse)(nil), // 1: pb.LogoutAdminResponse
}
var file_rpc_logout_admin_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_logout_admin_proto_init() }
func file_rpc_logout_admin_proto_init() {
	if File_rpc_logout_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_logout_admin_proto_rawDesc), len(file_rpc_logout_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_logout_admin_proto_goTypes,
		DependencyIndexes: file_rpc_logout_admin_proto_depIdxs,
		MessageInfos:      file_rpc_logout_admin_proto_msgTypes,
	}.Build()
	File_rpc_logout_admin_proto = out.File
	file_rpc_logout_admin_proto_goTypes = nil
	file_rpc_logout_admin_proto_depIdxs = nil
}
