// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: service_nostalgia.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Nostalgia_CreateArticle_FullMethodName     = "/pb.Nostalgia/CreateArticle"
	Nostalgia_DeleteArticle_FullMethodName     = "/pb.Nostalgia/DeleteArticle"
	Nostalgia_ListArticles_FullMethodName      = "/pb.Nostalgia/ListArticles"
	Nostalgia_GetArticle_FullMethodName        = "/pb.Nostalgia/GetArticle"
	Nostalgia_UpdateArticle_FullMethodName     = "/pb.Nostalgia/UpdateArticle"
	Nostalgia_UploadFile_FullMethodName        = "/pb.Nostalgia/UploadFile"
	Nostalgia_PolishText_FullMethodName        = "/pb.Nostalgia/PolishText"
	Nostalgia_GetAIConfig_FullMethodName       = "/pb.Nostalgia/GetAIConfig"
	Nostalgia_UpdateAIConfig_FullMethodName    = "/pb.Nostalgia/UpdateAIConfig"
	Nostalgia_ListAIModels_FullMethodName      = "/pb.Nostalgia/ListAIModels"
	Nostalgia_CreateCategory_FullMethodName    = "/pb.Nostalgia/CreateCategory"
	Nostalgia_DeleteCategory_FullMethodName    = "/pb.Nostalgia/DeleteCategory"
	Nostalgia_UpdateCategory_FullMethodName    = "/pb.Nostalgia/UpdateCategory"
	Nostalgia_ListCategories_FullMethodName    = "/pb.Nostalgia/ListCategories"
	Nostalgia_ListAllCategories_FullMethodName = "/pb.Nostalgia/ListAllCategories"
)

// NostalgiaClient is the client API for Nostalgia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NostalgiaClient interface {
	CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*CreateArticleResponse, error)
	DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error)
	ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error)
	GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error)
	UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*UpdateArticleResponse, error)
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	PolishText(ctx context.Context, in *PolishTextRequest, opts ...grpc.CallOption) (*PolishTextResponse, error)
	GetAIConfig(ctx context.Context, in *GetAIConfigRequest, opts ...grpc.CallOption) (*GetAIConfigResponse, error)
	UpdateAIConfig(ctx context.Context, in *UpdateAIConfigRequest, opts ...grpc.CallOption) (*GetAIConfigResponse, error)
	ListAIModels(ctx context.Context, in *ListAIModelsRequest, opts ...grpc.CallOption) (*ListAIModelsResponse, error)
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	ListAllCategories(ctx context.Context, in *ListAllCategoriesRequest, opts ...grpc.CallOption) (*ListAllCategoriesResponse, error)
}

type nostalgiaClient struct {
	cc grpc.ClientConnInterface
}

func NewNostalgiaClient(cc grpc.ClientConnInterface) NostalgiaClient {
	return &nostalgiaClient{cc}
}

func (c *nostalgiaClient) CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*CreateArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateArticleResponse)
	err := c.cc.Invoke(ctx, Nostalgia_CreateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteArticleResponse)
	err := c.cc.Invoke(ctx, Nostalgia_DeleteArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArticlesResponse)
	err := c.cc.Invoke(ctx, Nostalgia_ListArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleResponse)
	err := c.cc.Invoke(ctx, Nostalgia_GetArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*UpdateArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateArticleResponse)
	err := c.cc.Invoke(ctx, Nostalgia_UpdateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, Nostalgia_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) PolishText(ctx context.Context, in *PolishTextRequest, opts ...grpc.CallOption) (*PolishTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolishTextResponse)
	err := c.cc.Invoke(ctx, Nostalgia_PolishText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) GetAIConfig(ctx context.Context, in *GetAIConfigRequest, opts ...grpc.CallOption) (*GetAIConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAIConfigResponse)
	err := c.cc.Invoke(ctx, Nostalgia_GetAIConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) UpdateAIConfig(ctx context.Context, in *UpdateAIConfigRequest, opts ...grpc.CallOption) (*GetAIConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAIConfigResponse)
	err := c.cc.Invoke(ctx, Nostalgia_UpdateAIConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) ListAIModels(ctx context.Context, in *ListAIModelsRequest, opts ...grpc.CallOption) (*ListAIModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAIModelsResponse)
	err := c.cc.Invoke(ctx, Nostalgia_ListAIModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCategoryResponse)
	err := c.cc.Invoke(ctx, Nostalgia_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCategoryResponse)
	err := c.cc.Invoke(ctx, Nostalgia_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCategoryResponse)
	err := c.cc.Invoke(ctx, Nostalgia_UpdateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, Nostalgia_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nostalgiaClient) ListAllCategories(ctx context.Context, in *ListAllCategoriesRequest, opts ...grpc.CallOption) (*ListAllCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllCategoriesResponse)
	err := c.cc.Invoke(ctx, Nostalgia_ListAllCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NostalgiaServer is the server API for Nostalgia service.
// All implementations must embed UnimplementedNostalgiaServer
// for forward compatibility.
type NostalgiaServer interface {
	CreateArticle(context.Context, *CreateArticleRequest) (*CreateArticleResponse, error)
	DeleteArticle(context.Context, *DeleteArticleRequest) (*DeleteArticleResponse, error)
	ListArticles(context.Context, *ListArticlesRequest) (*ListArticlesResponse, error)
	GetArticle(context.Context, *GetArticleRequest) (*GetArticleResponse, error)
	UpdateArticle(context.Context, *UpdateArticleRequest) (*UpdateArticleResponse, error)
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	PolishText(context.Context, *PolishTextRequest) (*PolishTextResponse, error)
	GetAIConfig(context.Context, *GetAIConfigRequest) (*GetAIConfigResponse, error)
	UpdateAIConfig(context.Context, *UpdateAIConfigRequest) (*GetAIConfigResponse, error)
	ListAIModels(context.Context, *ListAIModelsRequest) (*ListAIModelsResponse, error)
	CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error)
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error)
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error)
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	ListAllCategories(context.Context, *ListAllCategoriesRequest) (*ListAllCategoriesResponse, error)
	mustEmbedUnimplementedNostalgiaServer()
}

// UnimplementedNostalgiaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNostalgiaServer struct{}

func (UnimplementedNostalgiaServer) CreateArticle(context.Context, *CreateArticleRequest) (*CreateArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArticle not implemented")
}
func (UnimplementedNostalgiaServer) DeleteArticle(context.Context, *DeleteArticleRequest) (*DeleteArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteArticle not implemented")
}
func (UnimplementedNostalgiaServer) ListArticles(context.Context, *ListArticlesRequest) (*ListArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArticles not implemented")
}
func (UnimplementedNostalgiaServer) GetArticle(context.Context, *GetArticleRequest) (*GetArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticle not implemented")
}
func (UnimplementedNostalgiaServer) UpdateArticle(context.Context, *UpdateArticleRequest) (*UpdateArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateArticle not implemented")
}
func (UnimplementedNostalgiaServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedNostalgiaServer) PolishText(context.Context, *PolishTextRequest) (*PolishTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PolishText not implemented")
}
func (UnimplementedNostalgiaServer) GetAIConfig(context.Context, *GetAIConfigRequest) (*GetAIConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAIConfig not implemented")
}
func (UnimplementedNostalgiaServer) UpdateAIConfig(context.Context, *UpdateAIConfigRequest) (*GetAIConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAIConfig not implemented")
}
func (UnimplementedNostalgiaServer) ListAIModels(context.Context, *ListAIModelsRequest) (*ListAIModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAIModels not implemented")
}
func (UnimplementedNostalgiaServer) CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedNostalgiaServer) DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedNostalgiaServer) UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedNostalgiaServer) ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedNostalgiaServer) ListAllCategories(context.Context, *ListAllCategoriesRequest) (*ListAllCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllCategories not implemented")
}
func (UnimplementedNostalgiaServer) mustEmbedUnimplementedNostalgiaServer() {}
func (UnimplementedNostalgiaServer) testEmbeddedByValue()                   {}

// UnsafeNostalgiaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NostalgiaServer will
// result in compilation errors.
type UnsafeNostalgiaServer interface {
	mustEmbedUnimplementedNostalgiaServer()
}

func RegisterNostalgiaServer(s grpc.ServiceRegistrar, srv NostalgiaServer) {
	// If the following call pancis, it indicates UnimplementedNostalgiaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Nostalgia_ServiceDesc, srv)
}

func _Nostalgia_CreateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).CreateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_CreateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).CreateArticle(ctx, req.(*CreateArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_DeleteArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).DeleteArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_DeleteArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).DeleteArticle(ctx, req.(*DeleteArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_ListArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).ListArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_ListArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).ListArticles(ctx, req.(*ListArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_GetArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).GetArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_GetArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).GetArticle(ctx, req.(*GetArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_UpdateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).UpdateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_UpdateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).UpdateArticle(ctx, req.(*UpdateArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_PolishText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolishTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).PolishText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_PolishText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).PolishText(ctx, req.(*PolishTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_GetAIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).GetAIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_GetAIConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).GetAIConfig(ctx, req.(*GetAIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_UpdateAIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).UpdateAIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_UpdateAIConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).UpdateAIConfig(ctx, req.(*UpdateAIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_ListAIModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAIModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).ListAIModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_ListAIModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).ListAIModels(ctx, req.(*ListAIModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).DeleteCategory(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).UpdateCategory(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nostalgia_ListAllCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NostalgiaServer).ListAllCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nostalgia_ListAllCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NostalgiaServer).ListAllCategories(ctx, req.(*ListAllCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Nostalgia_ServiceDesc is the grpc.ServiceDesc for Nostalgia service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nostalgia_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Nostalgia",
	HandlerType: (*NostalgiaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateArticle",
			Handler:    _Nostalgia_CreateArticle_Handler,
		},
		{
			MethodName: "DeleteArticle",
			Handler:    _Nostalgia_DeleteArticle_Handler,
		},
		{
			MethodName: "ListArticles",
			Handler:    _Nostalgia_ListArticles_Handler,
		},
		{
			MethodName: "GetArticle",
			Handler:    _Nostalgia_GetArticle_Handler,
		},
		{
			MethodName: "UpdateArticle",
			Handler:    _Nostalgia_UpdateArticle_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _Nostalgia_UploadFile_Handler,
		},
		{
			MethodName: "PolishText",
			Handler:    _Nostalgia_PolishText_Handler,
		},
		{
			MethodName: "GetAIConfig",
			Handler:    _Nostalgia_GetAIConfig_Handler,
		},
		{
			MethodName: "UpdateAIConfig",
			Handler:    _Nostalgia_UpdateAIConfig_Handler,
		},
		{
			MethodName: "ListAIModels",
			Handler:    _Nostalgia_ListAIModels_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _Nostalgia_CreateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _Nostalgia_DeleteCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _Nostalgia_UpdateCategory_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _Nostalgia_ListCategories_Handler,
		},
		{
			MethodName: "ListAllCategories",
			Handler:    _Nostalgia_ListAllCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_nostalgia.proto",
}
