# Stage 1: Build frontend
FROM node:23-alpine AS build-frontend
WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ ./

ENV VITE_APP_BASE_URL=http://localhost:80/api

RUN npm run build

# Stage 2: Build backend
FROM node:23-alpine AS build-backend
WORKDIR /app/backend

COPY backend/package*.json ./
RUN npm ci

COPY backend/ ./

ENV VITE_APP_BASE_URL=http://localhost:80/v1

RUN npm run build

# Stage 3: Final nginx server
FROM nginx:alpine

# 设置时区
RUN apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

# 清理默认文件
RUN rm -rf /usr/share/nginx/html/*

# 拷贝构建后的静态资源
COPY --from=build-frontend /app/frontend/dist /usr/share/nginx/html/
COPY --from=build-backend /app/backend/dist /usr/share/nginx/html/backend/

# 拷贝 nginx 配置
COPY nginx.conf /etc/nginx/nginx.conf

# 日志文件夹
RUN mkdir -p /etc/nginx/logs && touch /etc/nginx/logs/error.log && \
    chmod 755 /etc/nginx/logs

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]